# Generated by Django 2.0.1 on 2018-01-13 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=150, null=True)),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
            ],
        ),
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrator', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.Book')),
                ('length', models.TimeField()),
                ('narrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Narrator')),
            ],
            bases=('books.book',),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, to='books.Author'),
        ),
    ]
