# Generated by Django 2.0.1 on 2018-01-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180115_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
