# Generated by Django 2.0.1 on 2018-01-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20180121_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='own',
        ),
        migrations.RemoveField(
            model_name='book',
            name='owned_by',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('PRINT', 'Print Book'), ('AUDIO', 'Audiobook'), ('EBOOK', 'eBook')], default='AUDIO', max_length=5),
        ),
    ]
